#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# === Config (edit if needed) ===
# DEPLOY_BASE="/var/www"
# KEEP_RELEASES=5
# CADDY_CONFIG="/etc/caddy/Caddyfile"
# SUDO=${SUDO:-sudo}
#
# # Apps mapping: app name -> source dir (relative to repo) and port
# declare -A APP_SRC=(
#   ["editor"]="apps/editor"
#     ["editor-server"]="apps/editor-server"
#     )
#     declare -A APP_PORT=(
#       ["editor"]="3000"
#         ["editor-server"]="3001"
#         )
#
#         SERVICE_SUFFIX=".service"
#
#         log() { printf '%s\n' ">> $*"; }
#         err() { printf '%s\n' "!! $*" >&2; }
#         timestamp() { date -u +%Y%m%d%H%M%S; }
#
#         detect_mode() {
#           local src="$1"
#             if [ -f "$src/package.json" ]; then
#                 if grep -q '"build"' "$src/package.json" 2>/dev/null; then
#                       echo "static"; return
#                           fi
#                               if [ -f "$src/server.js" ] || [ -f "$src/index.js" ] || grep -q '"express"' "$src/package.json" 2>/dev/null; then
#                                     echo "node"; return
#                                         fi
#                                           fi
#                                             for d in dist build public; do
#                                                 if [ -d "$src/$d" ]; then
#                                                       echo "static"; return
#                                                           fi
#                                                             done
#                                                               if [ -f "$src/server.js" ] || [ -f "$src/index.js" ]; then
#                                                                   echo "node"
#                                                                     else
#                                                                         echo "static"
#                                                                           fi
#                                                                           }
#
#                                                                           find_build_dir() {
#                                                                             local src="$1"
#                                                                               for d in dist build public; do
#                                                                                   if [ -d "$src/$d" ]; then
#                                                                                         printf '%s' "$src/$d"; return
#                                                                                             fi
#                                                                                               done
#                                                                                                 printf ''
#                                                                                                 }
#
#                                                                                                 make_release_dir() {
#                                                                                                   local app="$1" ts
#                                                                                                     ts=$(timestamp)
#                                                                                                       local release_dir="$DEPLOY_BASE/$app/releases/$ts"
#                                                                                                         mkdir -p "$release_dir"
#                                                                                                           printf '%s' "$release_dir"
#                                                                                                           }
#
#                                                                                                           activate_current() {
#                                                                                                             local app="$1" release_dir="$2" current_dir="$DEPLOY_BASE/$app/current"
#                                                                                                               ln -sfn "$release_dir" "$current_dir"
#                                                                                                                 $SUDO chown -R "$(whoami)":"$(whoami)" "$DEPLOY_BASE/$app/releases" || true
#                                                                                                                 }
#
#                                                                                                                 prune_releases() {
#                                                                                                                   local app="$1" releases_dir="$DEPLOY_BASE/$app/releases"
#                                                                                                                     [ -d "$releases_dir" ] || return
#                                                                                                                       local to_delete
#                                                                                                                         to_delete=$(ls -1dt "$releases_dir"/* 2>/dev/null || true)
#                                                                                                                           local arr=()
#                                                                                                                             while IFS= read -r p; do arr+=("$p"); done <<<"$to_delete"
#                                                                                                                               local count=${#arr[@]}
#                                                                                                                                 if [ "$count" -le "$KEEP_RELEASES" ]; then return; fi
#                                                                                                                                   local i
#                                                                                                                                     for ((i=KEEP_RELEASES;i<count;i++)); do
#                                                                                                                                         log "Pruning old release: ${arr[i]}"
#                                                                                                                                             rm -rf "${arr[i]}"
#                                                                                                                                               done
#                                                                                                                                               }
#
#                                                                                                                                               rollback_app() {
#                                                                                                                                                 local app="$1" releases_dir="$DEPLOY_BASE/$app/releases"
#                                                                                                                                                   [ -d "$releases_dir" ] || { err "No releases to rollback for $app"; return 1; }
#                                                                                                                                                     IFS=$'\n' read -r -d '' -a rels < <(ls -1dt "$releases_dir"/* 2>/dev/null && printf '\0')
#                                                                                                                                                       if [ "${#rels[@]}" -lt 2 ]; then err "No previous release to rollback to for $app"; return 1; fi
#                                                                                                                                                         local prev="${rels[1]}"
#                                                                                                                                                           log "Rolling back $app -> $prev"
#                                                                                                                                                             ln -sfn "$prev" "$DEPLOY_BASE/$app/current"
#                                                                                                                                                             }
#
#                                                                                                                                                             caddy_reload() {
#                                                                                                                                                               if $SUDO caddy validate --config "$CADDY_CONFIG"; then
#                                                                                                                                                                   $SUDO systemctl reload caddy
#                                                                                                                                                                     else
#                                                                                                                                                                         err "Caddy validation failed"
#                                                                                                                                                                             return 1
#                                                                                                                                                                               fi
#                                                                                                                                                                               }
#
#                                                                                                                                                                               smoke_check() {
#                                                                                                                                                                                 local app="$1" mode="$2" port="${APP_PORT[$app]}" current="$DEPLOY_BASE/$app/current"
#                                                                                                                                                                                   if [ "$mode" = "node" ]; then
#                                                                                                                                                                                       sleep 1
#                                                                                                                                                                                           local code
#                                                                                                                                                                                               code=$($SUDO curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "http://127.0.0.1:${port}/" || true)
#                                                                                                                                                                                                   if [ "$code" = "200" ] || [ -n "$code" -a "$code" -lt 400 ]; then
#                                                                                                                                                                                                         log "Smoke OK: $app (http://127.0.0.1:${port}/) -> $code"
#                                                                                                                                                                                                               return 0
#                                                                                                                                                                                                                   else
#                                                                                                                                                                                                                         err "Smoke FAILED for $app -> HTTP $code"
#                                                                                                                                                                                                                               return 1
#                                                                                                                                                                                                                                   fi
#                                                                                                                                                                                                                                     else
#                                                                                                                                                                                                                                         if [ -f "$current/index.html" ]; then
#                                                                                                                                                                                                                                               log "Smoke OK: $app static index found"
#                                                                                                                                                                                                                                                     return 0
#                                                                                                                                                                                                                                                         else
#                                                                                                                                                                                                                                                               err "Smoke FAILED for $app: index.html missing in $current"
#                                                                                                                                                                                                                                                                     return 1
#                                                                                                                                                                                                                                                                         fi
#                                                                                                                                                                                                                                                                           fi
#                                                                                                                                                                                                                                                                           }
#
#                                                                                                                                                                                                                                                                           deploy_one() {
#                                                                                                                                                                                                                                                                             local app="$1" src="${APP_SRC[$app]:-}"
#                                                                                                                                                                                                                                                                               [ -n "$src" ] || { err "Unknown app: $app"; return 1; }
#                                                                                                                                                                                                                                                                                 [ -d "$src" ] || { err "Source dir missing: $src"; return 1; }
#
#                                                                                                                                                                                                                                                                                   local mode
#                                                                                                                                                                                                                                                                                     mode=$(detect_mode "$src")
#                                                                                                                                                                                                                                                                                       log "Deploying $app (mode=$mode) from $src"
#
#                                                                                                                                                                                                                                                                                         if [ -f "$src/package.json" ] && grep -q '"build"' "$src/package.json" 2>/dev/null; then
#                                                                                                                                                                                                                                                                                             log "Running npm ci && npm run build for $app"
#                                                                                                                                                                                                                                                                                                 (cd "$src" && npm ci && npm run build)
#                                                                                                                                                                                                                                                                                                   fi
#
#                                                                                                                                                                                                                                                                                                     local release_dir
#                                                                                                                                                                                                                                                                                                       release_dir=$(make_release_dir "$app")
#
#                                                                                                                                                                                                                                                                                                         if [ "$mode" = "static" ]; then
#                                                                                                                                                                                                                                                                                                             local bd
#                                                                                                                                                                                                                                                                                                                 bd=$(find_build_dir "$src")
#                                                                                                                                                                                                                                                                                                                     if [ -z "$bd" ]; then
#                                                                                                                                                                                                                                                                                                                           log "No build dir found; copying $src -> $release_dir"
#                                                                                                                                                                                                                                                                                                                                 rsync -a --delete "$src/" "$release_dir/"
#                                                                                                                                                                                                                                                                                                                                     else
#                                                                                                                                                                                                                                                                                                                                           log "Copying build output $bd -> $release_dir"
#                                                                                                                                                                                                                                                                                                                                                 rsync -a --delete "$bd/" "$release_dir/"
#                                                                                                                                                                                                                                                                                                                                                     fi
#                                                                                                                                                                                                                                                                                                                                                       else
#                                                                                                                                                                                                                                                                                                                                                           log "Copying project files $src -> $release_dir (excluding node_modules, .git)"
#                                                                                                                                                                                                                                                                                                                                                               rsync -a --exclude node_modules --exclude .git --exclude releases --exclude current "$src/" "$release_dir/"
#                                                                                                                                                                                                                                                                                                                                                                   local port="${APP_PORT[$app]}"
#                                                                                                                                                                                                                                                                                                                                                                       echo "PORT=${port:-3000}" > "$release_dir/.env"
#                                                                                                                                                                                                                                                                                                                                                                           echo "NODE_ENV=production" >> "$release_dir/.env"
#                                                                                                                                                                                                                                                                                                                                                                               (cd "$release_dir" && npm ci --production)
#                                                                                                                                                                                                                                                                                                                                                                                 fi
#
#                                                                                                                                                                                                                                                                                                                                                                                   activate_current "$app" "$release_dir"
#
#                                                                                                                                                                                                                                                                                                                                                                                     if [ "$mode" = "node" ]; then
#                                                                                                                                                                                                                                                                                                                                                                                         log "Restarting systemd service: ${app}${SERVICE_SUFFIX}"
#                                                                                                                                                                                                                                                                                                                                                                                             $SUDO systemctl daemon-reload || true
#                                                                                                                                                                                                                                                                                                                                                                                                 $SUDO systemctl restart "${app}${SERVICE_SUFFIX}"
#                                                                                                                                                                                                                                                                                                                                                                                                   fi
#                                                                                                                                                                                                                                                                                                                                                                                                   }
#
#                                                                                                                                                                                                                                                                                                                                                                                                   deploy_apps() {
#                                                                                                                                                                                                                                                                                                                                                                                                     local apps=("$@") deployed=()
#                                                                                                                                                                                                                                                                                                                                                                                                       for app in "${apps[@]}"; do
#                                                                                                                                                                                                                                                                                                                                                                                                           if deploy_one "$app"; then
#                                                                                                                                                                                                                                                                                                                                                                                                                 deployed+=("$app")
#                                                                                                                                                                                                                                                                                                                                                                                                                     else
#                                                                                                                                                                                                                                                                                                                                                                                                                           err "Deploy failed for $app -> attempting rollback for apps deployed so far"
#                                                                                                                                                                                                                                                                                                                                                                                                                                 for a in "${deployed[@]}"; do rollback_app "$a" || true; done
#                                                                                                                                                                                                                                                                                                                                                                                                                                       return 1
#                                                                                                                                                                                                                                                                                                                                                                                                                                           fi
#                                                                                                                                                                                                                                                                                                                                                                                                                                             done
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                               if ! caddy_reload; then
#                                                                                                                                                                                                                                                                                                                                                                                                                                                   err "Caddy reload failed -> rolling back all deployed apps"
#                                                                                                                                                                                                                                                                                                                                                                                                                                                       for a in "${deployed[@]}"; do rollback_app "$a" || true; done
#                                                                                                                                                                                                                                                                                                                                                                                                                                                           $SUDO systemctl reload caddy || true
#                                                                                                                                                                                                                                                                                                                                                                                                                                                               return 1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fi
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                   for app in "${deployed[@]}"; do
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                       local mode
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                           mode=$(detect_mode "${APP_SRC[$app]}")
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if ! smoke_check "$app" "$mode"; then
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     err "Smoke check failed for $app -> rolling back all deployed apps"
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           for a in "${deployed[@]}"; do rollback_app "$a" || true; done
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 caddy_reload || true
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return 1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fi
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             done
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               for app in "${deployed[@]}"; do prune_releases "$app" || true; done
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 log "Deployment complete for: ${deployed[*]}"
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 usage() {
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   cat <<EOF
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Usage: $0 <command> [app]
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Commands:
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     deploy [editor|editor-server|all]   Build & deploy apps (default: all)
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       rollback <app>                      Rollback <app> to previous release
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         prune <app>                         Prune old releases for <app>
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           status <app>                        Show current release for <app>
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           EOF
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             exit 1
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cmd=${1:-deploy}
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             target=${2:-all}
#
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             case "$cmd" in
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               deploy)
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   apps_to_run=()
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if [ "$target" = "all" ]; then
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for k in "${!APP_SRC[@]}"; do apps_to_run+=("$k"); done
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 else
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       apps_to_run+=("$target")
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fi
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               deploy_apps "${apps_to_run[@]}"
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ;;
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     rollback)
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if [ -z "${target:-}" ] || [ "$target" = "all" ]; then err "Please specify an app to rollback"; usage; fi
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             rollback_app "$target"
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 caddy_reload || true
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;;
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       prune)
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if [ -z "${target:-}" ] || [ "$target" = "all" ]; then err "Please specify an app to prune"; usage; fi
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               prune_releases "$target"
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ;;
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     status)
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if [ -z "${target:-}" ] || [ "$target" = "all" ]; then err "Please specify an app"; usage; fi
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             echo "CURRENT -> $DEPLOY_BASE/$target/current"
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ls -l "$DEPLOY_BASE/$target/current" || true
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;;
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       *)
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           usage
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ;;
	#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               esac
